spring.application.name=doc-manager-kotlin-demo

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:public.pem
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://myapp.com/auth