spring.application.name=doc-manager-kotlin-demo
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.oauth2.jwt=TRACE


spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:public.pem
